### ISSUE TITLE
Sprache nicht auswählbar

### ISSUE THREAD

**Issue by PACIFISTA1993** [Andy2244/jellyfin-androidtv-zidoo#1]
### Describe the bug

Habe eig von allem das neuste und kann die Sprache leider nicht wechseln

### Application version

0.14.1

### Device information

Zidoo Z1000 Pro

### Android version

9

### Jellyfin server version

10.8.1

**Comment by Andy2244** [comment]
> kann die Sprache leider nicht wechseln

Welche Sprache und wo? Audio/Subtitle/Ui ?
Brauche etwas mehr info.

**Comment by LUCASINO1993** [comment]
> > kann die Sprache leider nicht wechseln
> 
> Welche Sprache und wo? Audio/Subtitle/Ui ? Brauche etwas mehr info.

Hat sich erledigt, gemäss deinen letzten Beiträgen im Forum:) Danke
